change structure and start issue 3
pspaczek/CodersCamp2020JavaScript pull request #32
Opened 2021-01-07 18:48 UTC by DaveTheWebDev

Structure changed, added some folders, changed CSS to SCSS, started issue 3#

2021-01-07 21:50 UTC, ZibiH reviewed
Everything looks OK, only missing 'i' in scss file name '_variables'

2021-01-09 17:05 UTC, ZibiH reviewed
I like the changes, I think we can and should merge it ASAP

2021-01-10 16:41 UTC, pspaczek requested changes

2021-01-10 16:41 UTC, pspaczek commented on src/app/App.js
> +  game.start()
Question (Q): do you want to do something more in this function? I think here you should build a complete view here and keep the logic in deeper components :)

2021-01-10 16:41 UTC, pspaczek commented on src/app/Game.js
> +import menuOptionsObj from './components/MenuOptions';
IMO you can do this in App.js, it will be the initial view of your app :)

2021-01-10 16:41 UTC, pspaczek commented on src/app/Game.js
> +    const menuOptions = menuOptionsObj.render()
R: maybe you can pass listener ass menu options like new menuOptionsObj({class: 'button button--big', on:()=>{...}}) and keep fully responsibility inside these component. Now you have a few place when you have logic for this component :)

2021-01-10 16:41 UTC, pspaczek commented on src/app/components/MenuOptions.js
> +  render() {
R: add event listeners here from component config passed in App :)

2021-01-10 16:41 UTC, pspaczek commented on src/app/components/MenuOptions.js
> +    if (activeMode === 'people') {
do you need if/else? you return activeMode -> activeMode === 'people' return 'people' no idea why we need if. But, if you want to do something more then use switch ;)

2021-01-10 16:41 UTC, pspaczek commented on src/app/tools/renderElement.js
> +const possibleHTMLTags = ["a", "abbr", "acronym", "address", "applet", "area", "article", "aside", "audio", "b", "base", "basefont", "bdi", "bdo", "bgsound", "big", "blink", "blockquote", "body", "br
looks nice, maybe it can add listeners too :)

2021-01-10 16:41 UTC, pspaczek commented on styles/components/_MenuOptions.scss
> +  width: 1200px;
use rem instead of px

2021-01-10 16:41 UTC, pspaczek commented on styles/components/_MenuOptions.scss
> +    &--active::after {
for me 👇 this looks cleaner 
```
&--active {
  &::after {
    ...
  }
}
```

2021-01-10 16:41 UTC, pspaczek commented on src/app/tools/renderElement.js
> +const renderElement = (tagHTML, className, innerText = '', parentElement = quizMainNode, ) => {
WDYT about destructuring and use object to pass options :)

2021-01-10 20:36 UTC, merged